### PR TITLE
Current Cube RC1.

### PR DESCRIPTION
**Pull request by dkorolev**
Hi @mzhurovich && @sompylasar,

Happy 4th of July! :fireworks: 

Thanks,
Dima

### CODE REVIEW

**Comment by dkorolev** [comment]
As a matter of fact, what takes under 20 seconds on Mac runs for almost an hour on my Ubuntu now, taking 200+% of CPU.

```
27755 dima      20   0  578632 385028   1892 R 242.2  4.8  53:12.59 v2
```

It's done with stdin, just processing already cached entries. I'll have to investigate it some time soon.

**Comment by dkorolev** [comment]
(Of course, I've confirmed on CTFO data, which is much smaller so far, that Ubuntu and Mac produce the same results.)

**Comment by mzhurovich** [comment]
@dkorolev Debug build or in release too?

**Comment by dkorolev** [comment]
@mzhurovich Release too. Profiling now, but it's probably best to put the results of profiling into a separate pull request.

**Comment by mzhurovich** [comment]
@dkorolev Ok! Merging.

**Comment by dkorolev** [comment]
Thank you!

On Sunday, July 5, 2015, Maxim Zhurovich notifications@github.com wrote:

> @dkorolev https://github.com/dkorolev Ok! Merging.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KnowSheet/SimpleDashboard/pull/9#issuecomment-118653381
> .

## 

And, as always, have a nice day!
Dima

http://dimakorolev.com/ | http://www.linkedin.com/in/dimakorolev |
dmitry.korolev@gmail.com | +1 (312) 593 2783

**Pull request merged**
